sudo: required

language: node_js
node_js:
  - "node"
  - "7"

services:
  - docker

before_install:
  - docker build -t chibitronics/ltc-compiler-amd64 .
  - docker run --name ltc-compile-node -d -p 127.0.0.1:80:80 chibitronics/ltc-compiler-amd64
  - docker ps -a

script:
  - docker ps | grep ltc-compile-node

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push chibitronics/ltc-compiler-amd64;
    fi