sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t chibitronics/ltc-compiler-amd64:local .
  - docker run --name ltc-compile-node -d -p 127.0.0.1:80:80 chibitronics/ltc-compiler-amd64:local
  - docker ps -a

script:
  - docker ps | grep ltc-compile-node

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://index.docker.io/v1/ &&
    docker tag chibitronics/ltc-compiler-amd64:local chibitronics/ltc-compiler-amd64:latest &&
    docker push chibitronics/ltc-compiler-amd64:latest;
    fi