#!/bin/sh

config_file=/var/www/html/settings.php

echo "<?php" > ${config_file}
echo "class Settings {" >> ${config_file}

# COMPILE_TIMEOUT: The maximum number of seconds a compile can run for.  Defaults to 20.
if [ ! -z "${COMPILE_TIMEOUT}" ]
then
    echo "    const timeout = ${COMPILE_TIMEOUT};" >> ${config_file}
fi

# COMPILE_TIMEOUT_COLD: The maximum number of seconds the first compile can run for when the cache is missing (i.e. the first time.)
if [ ! -z "${COMPILE_TIMEOUT_COLD}" ]
then
    echo "    const cold_timeout = ${COMPILE_TIMEOUT_COLD};" >> ${config_file}
fi

# MEMORY_LIMIT_PCT: The limit at which /healthcheck will report "out of memory"
if [ ! -z "${MEMORY_LIMIT_PCT}" ]
then
    echo "    const low_memory_threshold = ${MEMORY_LIMIT_PCT};" >> ${config_file}
fi

echo "}" >> ${config_file}
echo "?>" >> ${config_file}


echo 'RewriteEngine on' > /etc/apache2/mods-enabled/rewrite.conf
echo '<Directory "/var/www/html">' >> /etc/apache2/mods-enabled/rewrite.conf
echo '  FallbackResource "index.php"' >> /etc/apache2/mods-enabled/rewrite.conf
echo '</Directory>' >> /etc/apache2/mods-enabled/rewrite.conf

exec apache2-foreground "$@"