#!/bin/sh

# Redirect all accesses to /index.php
cat > /etc/apache2/conf-enabled/rewrite-uri.conf <<EOF
<Directory "/var/www/html">
        RewriteEngine On
        RewriteBase "/var/www/htdocs"
        RewriteCond %{REQUEST_URI} !^/index.php$
        RewriteRule ^(.+)$ /index.php?$1 [NC,L]
</Directory>
EOF

# Add configuration variables for compile timeouts
# Run with "-e COMPILE_TIMEOUT=8 -e COMPILE_TIMEOUT_COLD=23"
settingsfile=/var/www/htdocs/settings.php
echo "<?php" > ${settingsfile}

if [ ! -z "${COMPILE_TIMEOUT}" ]
then
    echo -n "const timeout = '" >> ${settingsfile}
    echo ${COMPILE_TIMEOUT} | tr -d -c '[0-9]' >> ${settingsfile}
    echo "';" >> ${settingsfile}
fi

if [ ! -z "${COMPILE_TIMEOUT_COLD}" ]
then
    echo -n "const cold_timeout = '" >> ${settingsfile}
    echo ${COMPILE_TIMEOUT_COLD} | tr -d -c '[0-9]' >> ${settingsfile}
    echo "';" >> ${settingsfile}
fi

echo "?>" >> ${settingsfile}

exec apache2-foreground "$@"
